services:
  server:
    image: stm-back
    container_name: stm-back
    build:
      .
    ports:
      - 2000:2000
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stm-db:5432/stm
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    image: postgres
    container_name: stm-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stm
    ports:
      - 5000:5432
